### ISSUE TITLE
Error while adding txt record

### ISSUE THREAD

**Issue by milindpatel63** [AMEST/DotNetCertBot#7]
I'm running it in docker
```
Unhandled exception. OpenQA.Selenium.WebDriverTimeoutException: Timed out after 40 seconds
 ---> OpenQA.Selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@data-testid = 'zone-cards']"}
  (Session info: headless chrome=97.0.4692.99)
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition)
   --- End of inner exception stack trace ---
   at OpenQA.Selenium.Support.UI.DefaultWait`1.ThrowTimeoutException(String exceptionMessage, Exception lastException)
   at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition)
   at DotNetCertBot.CloudFlareUserApi.CloudFlareServiceSelenium.<>c__DisplayClass11_0.<<GoToZoneDns>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at DotNetCertBot.CloudFlareUserApi.CloudFlareServiceSelenium.GoToZoneDns(String zone)
   at DotNetCertBot.CloudFlareUserApi.CloudFlareServiceSelenium.AddChallenge(DnsChallenge challenge, String zoneName)
   at DotNetCertBot.Host.CertificateService.Issue()
   at DotNetCertBot.Host.Program.<Main>(String[] args)
```

**Comment by AMEST** [comment]
Fixed elements timeout, updated user agent's with actual versions (UI elements were different for older versions of browsers and this caused problems). Also a couple of minor fixes.

Now it should work fine (tested under different OS located in different countries)

[v0.2.10](https://github.com/AMEST/DotNetCertBot/releases/tag/v0.2.10)
